name: CI
"on":
  push: null
  schedule:
  - cron: 01 13 * * SAT
jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Setup
      run: |
        $env:PATH+=";$env:USERPRFILE\go\bin"
        go install mvdan.cc/gofumpt@latest
        gofumpt --version
    - name: Build
      run: |
        goreleaser --snapshot --clean
