name: CI
"on":
  push: null
  schedule:
  - cron: 01 13 * * SAT
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up Go
      uses: actions/setup-go@v4
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        distribution: goreleaser
        version: latest
        #args: release --clean
        #args: build --snapshot --clean        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
