name: CI
"on":
  push: null
  schedule:
  - cron: 01 13 * * SAT
jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Setup
      run: |
        go install mvdan.cc/gofumpt@latest
    - name: Build
      run: |
        gofumpt -w $<
        goreleaser build --single-target --snapshot --clean
