name: CI
"on":
  push: null
  schedule:
  - cron: 01 13 * * SAT
jobs:
  buildx:
    runs-on: windows-2019
    steps:
    - name: Get short SHA
      run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 8))" >>$env:GITHUB_ENV
